version: "3.7"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
    networks:
      - backend
      - frontend
  mongo_db:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
    networks:
      - backend

  app-client:
      build:
        context: react-frontend
        dockerfile: Dockerfile
        args:
          REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
      ports:
        - 3000:3000
      restart: always
      depends_on:
        - server
      networks:
        - frontend

volumes:
  db-data:

networks:
  backend:
  frontend: